

let categories_query = ['ANTIQUES%20%26%20COLLECTIBLES', 'ARCHITECTURE', 'ART', 'BIBLES', 'BIOGRAPHY%20%26%20AUTOBIOGRAPHY', 'BUSINESS%20%26%20ECONOMICS',
                    'COMICS%20%26%20GRAPHIC%20NOVELS', 'COMPUTERS', 'COOKING', 'CRAFTS%20%26%20HOBBIES', 'DESIGN', 'DRAMA', 'EDUCATION', 'FAMILY%20%26%20RELATIONSHIPS', 'FICTION',
                    'GAMES%20%26%20ACTIVITIES', 'GARDENING', 'HEALTH%20%26%20FITNESS', 'HISTORY', 'HOUSE%20%26%20HOME', 'HUMOR','LANGUAGE%20ARTS%20%26%20DISCIPLINES', 
                    'LAW', 'LITERARY%20COLLECTIONS', 'LITERARY%20CRITICISM', 'MATHEMATICS', 'MEDICAL','MUSIC', 'NATURE', 'PETS', 'PHILOSOPHY', 'PHOTOGRAPHY', 'POETRY', 
                    'POLITICAL%20SCIENCE', 'PSYCHOLOGY', 'REFERENCE', 'RELIGION', 'SCIENCE', 'SELF-HELP','SOCIAL%20SCIENCE', 'SPORTS%20%26%20RECREATION', 'STUDY%20AIDS', 
                    'TECHNOLOGY%20%26%20ENGINEERING', 'TRANSPORTATION', 'TRAVEL']

let categories_names = ['ANTIQUES & COLLECTIBLES', 'ARCHITECTURE', 'ART', 'BIBLES', 'BIOGRAPHY & AUTOBIOGRAPHY', 'BUSINESS & ECONOMICS',
                    'COMICS & GRAPHIC NOVELS', 'COMPUTERS', 'COOKING', 'CRAFTS & HOBBIES', 'DESIGN', 'DRAMA', 'EDUCATION', 'FAMILY & RELATIONSHIPS', 'FICTION',
                    'GAMES & ACTIVITIES', 'GARDENING', 'HEALTH & FITNESS', 'HISTORY', 'HOUSE & HOME', 'HUMOR', 'LANGUAGE ARTS & DISCIPLINES', 
                    'LAW', 'LITERARY COLLECTIONS', 'LITERARY CRITICISM', 'MATHEMATICS', 'MEDICAL', 'MUSIC', 'NATURE', 'PETS', 'PHILOSOPHY', 'PHOTOGRAPHY', 
                    'POETRY', 'POLITICAL SCIENCE', 'PSYCHOLOGY', 'REFERENCE', 'RELIGION', 'SCIENCE', 'SELF-HELP', 'SOCIAL SCIENCE', 'SPORTS & RECREATION', 'STUDY AIDS', 
                    'TECHNOLOGY & ENGINEERING', 'TRANSPORTATION', 'TRAVEL']


module.exports = {categories_names, categories_query}